name: RAUCA
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiofiles=22.1.0
  - aiosqlite=0.18.0
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=23.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - bleach=4.1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - cffi=1.15.1
  - comm=0.1.2
  - cryptography=41.0.3
  - cuda-version=11.7
  - cudatoolkit=11.7.0
  - cupy=10.4.0
  - cutensor=1.5.0.3
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.0.4
  - executing=0.8.3
  - expat=2.5.0
  - fontconfig=2.14.1
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - idna=3.4
  - importlib_metadata=6.0.0
  - importlib_resources=5.2.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=1.23.4
  - jupyter_server_fileid=0.9.0
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.4
  - jupyterlab=3.6.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.22.0
  - jupyterlab_widgets=3.0.5
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libopenblas=0.3.20
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - libxslt=1.1.37
  - lxml=4.9.3
  - lz4-c=1.9.4
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - munkres=1.1.4
  - mysql=5.7.24
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.9.2
  - nccl=2.12.12.1
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.89.1
  - nvidia-ml-py=12.535.133
  - nvitop=1.3.2
  - openssl=3.0.13
  - packaging=23.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.2.1
  - platformdirs=3.10.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.17
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python_abi=3.9
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.4.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - readline=8.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - send2trash=1.8.0
  - setuptools=68.0.0
  - sip=6.6.2
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.4
  - sqlite=3.41.2
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.3.2
  - traitlets=5.7.1
  - typing_extensions=4.7.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - widgetsnbextension=4.0.5
  - xz=5.4.2
  - y-py=0.5.9
  - yaml=0.2.5
  - ypy-websocket=0.8.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - absl-py==1.4.0
    - appdirs==1.4.4
    - cachetools==5.3.1
    - chainer==7.8.1
    - charset-normalizer==2.1.1
    - click==8.1.6
    - cmake==3.25.0
    - contourpy==1.1.0
    - docker-pycreds==0.4.0
    - fastrlock==0.8.1
    - filelock==3.9.0
    - fire==0.5.0
    - fonttools==4.42.0
    - gitdb==4.0.10
    - gitpython==3.1.32
    - google-auth==2.22.0
    - google-auth-oauthlib==1.0.0
    - grpcio==1.56.2
    - imageio==2.27
    - importlib-metadata==6.8.0
    - importlib-resources==6.0.1
    - ipdb==0.13.13
    - kornia==0.7.1
    - lazy-loader==0.3
    - lit==15.0.7
    - loralib==0.1.2
    - markdown==3.4.4
    - markupsafe==2.1.2
    - memory-profiler==0.61.0
    - mpmath==1.2.1
    - networkx==3.0
    - numpy==1.25.2
    - oauthlib==3.2.2
    - opencv-python==4.8.0.74
    - pandas==2.0.3
    - pathtools==0.1.2
    - pillow==10.0.0
    - protobuf==4.23.4
    - psutil==5.9.5
    - py-cpuinfo==9.0.0
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pycocotools==2.0.6
    - pytz==2023.3
    - pywavelets==1.4.1
    - pyyaml==6.0.1
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-image==0.21.0
    - scipy==1.11.1
    - seaborn==0.11.0
    - sentry-sdk==1.29.2
    - setproctitle==1.3.2
    - smmap==5.0.0
    - sympy==1.11.1
    - tensorboard==2.13.0
    - tensorboard-data-server==0.7.1
    - termcolor==2.3.0
    - thop==0.1.1-2209072238
    - tifffile==2023.7.18
    - tqdm==4.65.1
    - triton==2.0.0
    - typing-extensions==4.4.0
    - tzdata==2023.3
    - ultralytics==8.0.154
    - urllib3==1.26.13
    - werkzeug==2.3.6
    - zipp==3.16.2
